#!/bin/sh

# Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Git
brew install git

# Set up dotfiles
git clone git@github.com:kriskhaira/dotfiles.git ~/code/dotfiles
ln -s ~/code/dotfiles ~/.dotfiles

# RCM
brew tap thoughtbot/formulae
brew install rcm
rcup

# Useful tools
brew install openssl
brew install reattach-to-user-namespace
brew install zsh
brew cask install --appdir="/Applications" backblaze
brew install m-cli
brew cask install --appdir="/Applications" keycastr
brew cask install --appdir="/Applications" istat-menus

# Ruby
brew install rbenv
brew install ruby-build
rbenv install 2.3.0
rbenv global 2.3.0
gem install rubocop
gem install yard

# Node
brew install node
brew install yarn
echo "Installing NVM"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
nvm install 4.4.0
nvm use 4.4.0
nvm alias default 4.4.0

# Other Languages
brew cask install --appdir="/Applications" dash
brew install Caskroom/cask/java
brew install leiningen
brew install golang

# Shell environments
brew install tmux
brew install tmate
gem install teamocil

# Vim & IDEs
brew install ctags
brew install sift
brew install the_silver_searcher
brew install pt
brew install ack
brew install rpl
brew cask install --appdir="/Applications" macvim
curl -L https://bit.ly/janus-bootstrap | bash
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
brew cask install --appdir="/Applications" atom
brew cask install --appdir="/Applications" macdown

# Image manipulation
brew install imagemagick
brew cask install --appdir="/Applications" xquartz
brew cask install --appdir="/Applications" inkscape

# GitHub/Git Tools
brew install hub
brew install git-flow
brew install tig
gem install git-up
brew install bfg

# Frontend tools
yarn global add netlify
yarn global add firebase
yarn global add bower
yarn global add ember-cli
brew install watchman
brew cask install glueprint

# Databases
brew install mysql
brew cask install --appdir="/Applications" sequel-pro

# Networking
brew install mobile-shell
brew cask install airvpn
brew cask install tunnelblick
brew cask install --appdir="/Applications" tunnelbear
brew cask install --appdir="/Applications" little-snitch
brew cask install --appdir="/Applications" transmit
brew install homebrew/binary/ngrok2
brew install wget
brew install httpie
yarn global add fast-cli
yarn global add speed-test

# Browsers
brew cask install --appdir="/Applications" brave
brew cask install --appdir="/Applications" vivaldi
brew cask install --appdir="/Applications" firefox

# PERSONAL -- move this to .local

# IM & Communications
brew cask install --appdir="/Applications" skype
brew cask install --appdir="/Applications" whatsapp
brew cask install --appdir="/Applications" screenhero

# Project Management
brew cask install omnigraffle
brew cask install --appdir="/Applications" google-drive
brew cask install --appdir="/Applications" harvest

# Productivity
brew cask install --appdir="/Applications" appzapper
brew cask install bartender
brew cask install --appdir="/Applications" textexpander
brew cask install --appdir="/Applications" alfred
brew cask install --appdir="/Applications" remember-the-milk
brew cask install --appdir="/Applications" libreoffice

# Run local
if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

