#!/bin/sh

# Set basic keyboard and mouse settings
# <Switch to Colemak>
# <Turn on tap to click>

# Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install Dropbox
brew install dropbox

# Install iTerm2
brew install iterm2
brew install tmux
gem install teamocil

# Set up dotfiles
git clone git@github.com:kriskhaira/dotfiles.git ~/code/dotfiles
ln -s ~/code/dotfiles ~/.dotfiles

# RCM
brew install rcm
rcup

# ?
brew install openssl
brew install reattach-to-user-namespace

# Install backblaze
brew install backblaze
brew install m-cli
brew install keycastr
brew install istat-menus

# Ruby
brew install rbenv
brew install ruby-build
rbenv install 2.3.0
rbenv global 2.3.0
gem install rubocop
gem install yard

# Node
brew install node
brew install yarn
echo "Installing NVM"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
nvm install 4.4.0
nvm use 4.4.0
nvm alias default 4.4.0

# Other Languages
brew install dash
brew install Caskroom/cask/java
brew install leiningen
brew install golang

# Vim & IDEs
brew install ctags
brew install sift
brew install the_silver_searcher
brew install pt
brew install ack
brew install rpl
brew install macvim
curl -L https://bit.ly/janus-bootstrap | bash
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
brew install atom
brew install macdown

# Image manipulation
brew install imagemagick
brew install xquartz
brew install inkscape

# GitHub/Git Tools
brew install hub
brew install git-flow
brew install tig
gem install git-up
brew install bfg

# Frontend tools
yarn global add netlify
yarn global add firebase
yarn global add bower
yarn global add ember-cli
brew install watchman
brew install glueprint

# Databases
brew install mysql
brew install sequel-pro

# Networking
brew install mosh
brew install airvpn
brew install tunnelblick
brew install tunnelbear
brew install little-snitch
brew install transmit
brew install homebrew/binary/ngrok2
brew install wget
brew install httpie
yarn global add fast-cli
yarn global add speed-test

# Browsers
brew install brave
brew install vivaldi
brew install firefox

# PERSONAL -- move this to .local

# Project Management
brew install omnigraffle
brew install google-drive
brew install harvest

# Productivity
brew install appzapper
brew install bartender
brew install textexpander
brew install alfred
brew install remember-the-milk
brew install libreoffice

# Run local
if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

