#!/bin/sh

# Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Git
brew install git

# Set up dotfiles
git clone git@github.com:kriskhaira/dotfiles.git ~/code/dotfiles
ln -s ~/code/dotfiles ~/.dotfiles

# RCM
brew tap thoughtbot/formulae
brew install rcm
rcup

# Useful tools
brew install openssl
brew install reattach-to-user-namespace
brew install zsh
brew install m-cli

# Ruby
brew install rbenv
brew install ruby-build
rbenv install 2.3.0
rbenv global 2.3.0
gem install yard

# Node
brew install node
echo "Installing NVM"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
nvm install 4.4.0
nvm use 4.4.0
nvm alias default 4.4.0

# Other Languages
brew install Caskroom/cask/java
brew install leiningen
brew install golang

# Shell environments
brew install tmux
brew install tmate
gem install teamocil

# Vim & IDEs
brew install ctags
brew install sift
brew install the_silver_searcher
brew install pt
brew install rpl
brew cask install macvim
curl -L https://bit.ly/janus-bootstrap | bash
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
brew cask install atom

# Image manipulation
brew install imagemagick
brew cask install --appdir="/Applications" xquartz
brew cask install --appdir="/Applications" inkscape

# GitHub/Git Tools
brew install hub
brew install git-flow
brew install tig
gem install git-up
brew install bfg

# Frontend tools
npm install -g netlify
npm install -g firebase
npm install -g bower
npm install -g ember-cli
brew install watchman
brew cask install glueprint

# Databases
brew install mysql
brew cask install sequel-pro

# Networking
brew install mobile-shell
brew cask install airvpn
brew cask install tunnelblick
brew cask install tunnelbear
brew install homebrew/binary/ngrok2
brew install wget
npm install --global fast-cli
npm install --global speed-test

# Browsers
brew cask install --appdir="/Applications" brave
brew cask install --appdir="/Applications" vivaldi
brew cask install --appdir="/Applications" firefox

# PERSONAL -- move this to .local

# IM & Communications
brew cask install skype
brew cask install whatsapp
brew cask install --appdir="/Applications" screenhero

# Project Management
brew cask install omnigraffle
brew cask install --appdir="/Applications" google-drive

# Productivity
brew cask install appzapper
brew cask install bartender
brew cask install textexpander
brew cask install --appdir="/Applications" alfred

# Run local
if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

